cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
file:
  upload-dir: /javauploads/Code/
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
email:
  subject: "Default subject"
  message: "Default message"
spring:
  application:
    name: rest-with-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: marl
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none # ao invés de "update", manter "none" porque agora é controlado por migrações com flyway
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect or MySQLDialect
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB
#spring.jpa.open-in-view
logging:
  level:
    root: INFO
    # net.sf.jasperreports.engine.*: TRACE
    # root: WARN
    # br.com.erudio: DEBUG
spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true