spring:
  application:
    name: rest-with-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: marl
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none # ao invés de "update", manter "none" porque agora é controlado por migrações com flyway
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect or MySQLDialect
    show-sql: false

    open-in-view: false
#spring.jpa.open-in-view
logging:
  level:
    root: INFO
    #root: WARN
    #br.com.erudio: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true